AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin-code-sql specific exceptions
#
Lint/BinaryOperatorWithIdenticalOperands: { Exclude: ['spec/**/*_spec.rb'] }
Naming/MethodParameterName: { Exclude: ['lib/ronin/code/sql/functions.rb'] }
